name: coffeecore
description: "A Flutter app for coffee farmers to manage market prices and farming data."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0" # Updated for clarity and future-proofing

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter/UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.2

  # Firebase and authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # File and media handling
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

  # Utilities and permissions
  http: ^1.3.0
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  provider: ^6.1.3
  vector_math: ^2.1.4
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  file_picker: ^10.1.2
  excel: ^4.0.6
  open_file: ^3.5.10
  share_plus: ^10.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/coffee_weather.jpg
    - assets/coffee_field_data.jpg
    - assets/coffee_pestdisease_management.jpg
    - assets/coffee_funds_management.jpg
    - assets/coffee_manuals.jpg
    - assets/coffee_farming_tips.jpg
    - assets/coffee_soil.jpg
    - assets/coffee-plant.png
    - assets/pests/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
