name: coffeecore
description: "A Flutter app for coffee farmers to manage market prices and farming data."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0" # Updated for clarity and future-proofing

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter/UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.0.0
  fl_chart: ^1.1.0

  # Firebase and authentication
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # File and media handling
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

  # Utilities and permissions
  http: ^1.3.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  provider: ^6.1.3
  vector_math: ^2.1.4
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  file_picker: ^10.1.2
  excel: ^4.0.6
  open_file: ^3.5.10
  share_plus: ^11.1.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.5
  custom_radio_grouped_button: ^2.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    #- assets/coffee_weather.jpg
    #- assets/coffee_field_data.jpg
    - assets/
    - assets/pests/
    - assets/diseases/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
